// next
import type { NextPage } from "next";

import Page from "../components/Page";

const Home: NextPage = () => {
  return (
    <Page
      title="Driflys"
      meta={
        <>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </>
      }
    >
      <h1>Welcome to Driflys</h1>
    </Page>
  );
};

export default Home;
