import { PreLaunchLayout } from "../layouts";

// components
import Page from "../components/Page";
import Hero from "../components/sections/Hero";

const Home = () => {
  return (
    <Page
      title="Driflys"
      meta={
        <>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </>
      }
    >
      <main>
        <Hero />
      </main>
    </Page>
  );
};

Home.layout = PreLaunchLayout;

export default Home;
