import { GetServerSidePropsContext } from "next";

import LandingLayout from "../../layouts/landing.layout";

// components
import Page from "../../components/Page";
import ContactUs from "../../components/sections/ContactUs";
import Hero from "../../components/sections/Hero";
import Features from "../../components/sections/Features";

const Home = () => {
  return (
    <Page
      title="Driflys"
      meta={
        <>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </>
      }
    >
      <main>
        <Hero />

        <Features />

        <ContactUs />
      </main>
    </Page>
  );
};

Home.layout = LandingLayout;

export default Home;

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  return {
    redirect: {
      destination: "/",
      permanent: false,
    },
  };
};
